# Sample pipeline configuration
# Before deploying, replace rbansal2 with your username (`echo rbansal2`)  and <kubernetes-cluster-vrn> with your cluster VRN.
name: rbansal2-hello-world-pipeline
description: A sample pipeline to print hello world on a schedule
kubernetes_cluster_vrn: <kubernetes-cluster-vrn>
namespace: default
manifest:
  config:
    environment_variables:
      - name: GREETING
        value: "Hello, World!"
  triggers:
    - name: rbansal2-schedule-5m-trigger
      vrn: vast:dataengine:triggers:rbansal2-schedule-5m-trigger
  function_deployments:
    - name: rbansal2-hello-world
      function_vrn: vast:dataengine:functions:rbansal2-hello-world
      revision: 1
  links:
      - source: ["rbansal2-schedule-5m-trigger"]
        destination: ["rbansal2-hello-world"]
